apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: slack-publisher
spec:
  template:
    spec:
      containers:
        - image: gcr.io/williamtsoi-knative-demo/slackevents:0.1.3
          env:
            - name: SLACK_CHANNEL
              valueFrom:
                secretKeyRef:
                  name: slack-notif-secrets
                  key: SLACK_CHANNEL
            - name: SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-notif-secrets
                  key: SLACK_TOKEN
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: slack-tweet-notifier
spec:
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: slack-publisher
