apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: eventstore
spec:
  template:
    spec:
      containers:
        - image: gcr.io/williamtsoi-knative-demo/eventstore:0.2.2
          env:
            - name: FIRESTORE_COLL_NAME
              value: knative-tweets
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: twitter-events-trigger
spec:
  filter:
    sourceAndType:
      type: com.twitter
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: eventstore
