apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: simple
  namespace: demo
spec:
  template:
    spec:
      containers:
        - image: gcr.io/williamtsoi-knative-demo/maxprime:latest
          env:
            - name: RELEASE
              value: "v0.2.1-simple"
